# docker-compose.yml

version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200" # elasticsearch HTTP 기본 포트. elasticsearch 서버에 대해 클라이언트가 HTTP API 호출을 시도할 수 있습니다.
      - "9300:9300" # elasticsearch TCP 기본 포트. 클러스터 내 elasticsearch 노드끼리 통신할 때 사용하는 포트입니다.
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m" # JVM 메모리 설정입니다.
      ELASTIC_PASSWORD: mypassword
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node # 색인을 위해 명시해주는 타입으로, 지금은 이 클러스터가 단일 노드로 구성되어있음을 나타냅니다.
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044" # filebeat에서 logstash로 연결되는 포트입니다.
      - "5000:5000/tcp" 
      - "5000:5000/udp" 
      - "9600:9600" 
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601" # kibana 기본 포트
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: